const AccordionInfo = [
  {
    id: 1,
    header: "legal",
    dataTarget: "#collapse-legal",
    link: "https://www.mynavyexchange.com/nex/sitemap",
    name: "Site Map",
    divId: "collapse-legal",
  },
  {
    id: 2,
    header: "legal",    
    dataTarget: "#collapse-legal",
    link: "https://www.mynavyexchange.com/nex/privacy",
    name: "Privacy Policy",
    divId: "collapse-legal",
  },
  {
    id: 3,
    header: "legal",    
    dataTarget: "#collapse-legal",
    link: "https://www.mynavyexchange.com/customerservice/contactUs.jsp",
    name: "Contact Us",
    divId: "collapse-legal",
  },
  {
    id: 4,
    header: "legal",    
    dataTarget: "#collapse-legal",
    link: "https://dodcio.defense.gov/DoDSection508/Std_Stmt.aspx",
    name: "508 Compliance",
    divId: "collapse-legal",
  },
  {
    id: 5,
    header: "legal",    
    dataTarget: "#collapse-legal",
    link: "https://www.foiaonline.gov/foiaonline/action/public/request",
    name: "FOIA",
    divId: "collapse-legal",
  },
  {
    id: 6,
    header: "Legal",    
    dataTarget: "#collapse-legal",
    link: "https://www.secnav.navy.mil/donhr/Site/Pages/No-Fear-Act.aspx#",
    name: "No Fear Act",
    divId: "collapse-legal",
  },
  {
    id: 7,
    header: "Our Partners",    
    dataTarget: "#collapse-OurPartners",
    link: "https://www.navy.com/",
    name: "Navy.com",
    divId: "collapse-OurPartners",
  },
];

export default AccordionInfo;